#!/bin/bash

####

#deklaracja odpowiednich zmiennych zgodnie z poleceniem

index="401183"
timestamp=$(date +'%m.%d.%Y')
zip_link="https://home.agh.edu.pl/~wsarlej/Customers_Nov2021.zip"
old_link="https://home.agh.edu.pl/~wsarlej/Customers_old.csv"
csv_name="Customers_Nov2021"
old_name="Customers_old"
passwd="agh"
address="tescik224@gmail.com"
dbuser="postgres"
dbname="postgres"
log="skrypt_${timestamp}.log"
[[ -f PROCESSED ]] && mkdir PROCESSED

#1a wget - sluzy do pobierania plikow z sieci

wget $zip_link && echo "Pobrano pomyslnie plik skompresowany .zip z sieci" > PROCESSED/$log

#1b unzip - rozpakowuje folder zip, -P - haslo(password), -d podaje folder

unzip -P $passwd $csv_name.zip && echo "Rozpakowano pomyslnie plik .zip " >> PROCESSED/$log

#1c Walidacja pliku

#Pobranie pliku Customers_old.csv
wget $old_link && echo "Pobrano pomyslnie plik .csv"  >> PROCESSED/$log

#Trzeba przeniesc plik .csv do folderu /tmp/ bo psql nie ma dostępu do mojego folderu domowego
mv $csv_name.csv /tmp/$csv_name.csv 

lines_in_first_file=$(cat /tmp/$csv_name.csv | wc -l)

awk 'NR == FNR{a[$0];next} $0 in a' $old_name.csv /tmp/$csv_name.csv | awk -F "," '{ if(length($0)>0) { print $0 }}' > $csv_name.bad.$timestamp && echo "Pomyslnie sprawdzono obecnosc duplikatow"  >> PROCESSED/$log

duplicates=$(cat $csv_name.bad.$timestamp | cut -d$'\n' -f2-  | wc -l)

awk 'NR == FNR{a[$0];next} !($0 in a)' $old_name.csv /tmp/$csv_name.csv | awk -F "," '{ if(length($0)>0) { print $0 }}' > temp.csv && echo "Pomyslnie wybrano unikatowe linie" >> PROCESSED/$log

cat temp.csv > /tmp/$csv_name.csv
rm temp.csv
correct_lines=$(cat /tmp/$csv_name.csv | wc -l)

#1d Tworzenie tabeli
#zeby dzialalo bez koniecznosci wpisywania hasla
#sudo visudo
#Defaults:username !authenticate

sudo -i -u $dbuser -H -- psql -d $dbname -c "CREATE TABLE IF NOT EXISTS CUSTOMERS_${index} (first_name VARCHAR(30), last_name VARCHAR(30), email VARCHAR(50), lat REAL, long REAL);" && echo "Pomyslnie utworzono tabele w bazie danych" >> PROCESSED/$log

#1e Ladowanie danych do tabeli

sudo -i -u $dbuser -H -- psql -d $dbname -c "\copy CUSTOMERS_${index} FROM '/tmp/${csv_name}.csv' WITH (FORMAT CSV, HEADER);" && echo "Pomyslnie zaladowano dane do tabeli w bazie danych" >> PROCESSED/$log

records=$(sudo -i -u $dbuser -H -- psql -d $dbname -c "SELECT COUNT(*) FROM CUSTOMERS_${index}" | sed '1,2d;4d' | tr --delete " \t") && echo "Pomyslnie zliczono rekordy w tabeli" >> PROCESSED/$log

#1f przeniesienie do podkatalogu PROCESSED

mv /tmp/${csv_name}.csv PROCESSED/${timestamp}_${csv_name}.csv && echo "Pomyslnie przeniesiono oczyszczony plik .csv do podkatalogu PROCESSED" >> PROCESSED/$log


#1g, 1h
#wyslanie maila z raportem
echo -e "Wierszy w pliku z internetu: $lines_in_first_file\nPoprawnych wierszy: $correct_lines\nDuplikatow w pliku wejsciowym: $duplicates\nDanych zaladowanych do tabeli: $records" | mail -s "CUSTOMERS LOAD - ${timestamp}" $address && echo "Pomyslnie wyslano pierwszego maila z raportem" >> PROCESSED/$log


#1i
#kwerenda SQL (50 km od pewnego punktu)
#instaluje postgisa: sudo apt-get install postgis postgresql-14-postgis-3
sudo -i -u $dbuser -H -- psql -d $dbname -c "CREATE EXTENSION IF NOT EXISTS postgis"

echo "SELECT first_name, last_name INTO BEST_CUSTOMERS_${index} FROM Customers_${index} WHERE ST_DWithin(ST_Point(lat,long)::geography, ST_Point(41.39988501005976,-75.67329768604034)::geography,50000)" > query.sql

#znowu trzeba przeniesc plik z folderu domowego do katalogu /tmp/ bo psql sie burzy
mv query.sql /tmp/query.sql

#opcja -f => zapewnia odczyt zapytania z pliku
sudo -i -u $dbuser -H -- psql -d $dbname -f /tmp/query.sql && echo "Pomyslnie przeprowadzono kwerende SQL w bazie danych" >> PROCESSED/$log

#1j - eksport wyniku ostatniego zapytania do pliku .csv
sudo -i -u $dbuser -H -- psql -d $dbname -c "\copy (SELECT * FROM BEST_CUSTOMERS_${index}) TO '/tmp/temp.csv' WITH (FORMAT CSV, HEADER)" && echo "Pomyslnie wyeksportowano tabele do pliku .csv" >> PROCESSED/$log

#1k Skompresowanie pliku

zip ${csv_name}_compressed.zip PROCESSED/${timestamp}_${csv_name}.csv && echo "Pomyslnie skompresowano plik" >> PROCESSED/$log

#1l Wyslanie maila z zipem

lines_in_second_file=$(cat PROCESSED/${timestamp}_${csv_name}.csv | wc -l)
echo -e "Data: $timestamp\nWierszy w pliku .csv: $lines_in_second_file" | mail -A ${csv_name}_compressed.zip -s "Temat" $address && echo "Pomyslnie wyslano maila z plikiem .zip" >> PROCESSED/$log


rm ${csv_name}.bad.${timestamp} ${csv_name}_compressed.zip ${csv_name}.zip PROCESSED/${timestamp}_${csv_name}.csv ${old_name}.csv

sudo -i -u postgres -H -- psql -d postgres -c "DROP TABLE CUSTOMERS_${index}; DROP TABLE BEST_CUSTOMERS_${index};"
